# cookie_secret_and_proxy_auth_token.yml
# An ansible playbook to create a cookie secret and proxy auth token

---
- hosts: jh_servers
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/host.yml
    # domain_name: mydomain.org
    # email: my.email@email.org

  tasks:
    - name: create /srv/jupyterhub directory
      file:
        path: /srv/jupyterhub
        owner: root
        group: sudo
        mode: '0760'
        state: directory
      become: yes
    
    # cookie_secret
    - name: Touch jupyterhub_cookie_secret file
      file:
        path: /srv/jupyterhub/jupyterhub_cookie_secret
        owner: root
        group: sudo
        mode: '0760'
        state: touch
      become: yes
    - name: Create cookie secret file with openssl using shell
      shell: openssl rand -hex 32 > /srv/jupyterhub/jupyterhub_cookie_secret
      args:
        executable: /bin/bash
      become: yes
    - name: Change jupyterhub_cookie_secret file permissions to 600
      file:
        path: /srv/jupyterhub/jupyterhub_cookie_secret
        owner: root
        group: sudo
        mode: '0600'
      become: yes
    
    # proxy_auth_token
    - name: Touch proxy_auth_token file
      file:
        path: /srv/jupyterhub/proxy_auth_token
        owner: root
        group: sudo
        mode: '0760'
        state: touch
      become: yes
    - name: Create proxy_auth_token file with openssl using shell
      shell: openssl rand -hex 32 > /srv/jupyterhub/proxy_auth_token
      args:
        executable: /bin/bash
      become: yes
    - name: Change proxy_auth_token file permissions to 600
      file:
        path: /srv/jupyterhub/proxy_auth_token
        owner: root
        group: sudo
        mode: '0600'
      become: yes
    
    # dhparam.pem
    - name: Touch dhparam.pem file
      file:
        path: /srv/jupyterhub/dhparam.pem
        owner: root
        group: sudo
        mode: '0760'
        state: touch
      become: yes
    - name: Create dhparam.pem file with openssl using shell... This can take a minute or two, be patient
      shell: openssl dhparam -out /srv/jupyterhub/dhparam.pem 2048
      args:
        executable: /bin/bash
      become: yes
    - name: Change dhparam.pem file permissions to 600
      file:
        path: /srv/jupyterhub/dhparam.pem
        owner: root
        group: sudo
        mode: '0600'
      become: yes
