---
- hosts: localhost
  vars:
    do_api_token: "{{ lookup('file','~/.do/do_api_token') }}"
    do_droplet_id: 177856941
  tasks:
  - name: Create Digital Ocean Server (Droplet)
    digital_ocean_droplet:
      state: present
      id: "{{ do_droplet_id }}"
      name: ansible-jh-server
      oauth_token: "{{ do_api_token }}"
      ssh_keys: "{{ ssh_key_array }}"
      size: 1gb
      region: sfo2
      image: ubuntu-18-04-x64
      wait_timeout: 500
      unique_name: yes
    register: my_droplet

  - debug:
      msg: "New Droplet - ID of droplet is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.droplet.networks.v4[0].ip_address }}"

  - name: Save DO Droplet IP address to Ansible fact variable
    set_fact:
      do_droplet_ip: "{{ my_droplet.data.droplet.networks.v4[0].ip_address }}"
      do_droplet_id: "{{ my_droplet.data.droplet.id }}"

## Need to put in a little wait here for server to fully start up.
## Maybe just 5 or 10 seconds

  - name: Ensure do_droplet_ip variable is saved as an Ansible fact
    debug:
      var: do_droplet_ip
