# cull_idle_servers.yml
# An Ansible playbook to add functionality that
# culls servers from jupyterhub that are idle

---
- hosts: jh_servers
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/host.yml
    - vars/college.yml
    # domain_name: mydomain.org

  tasks:
    - name: conda install python-dateutil into jupyterhub conda env from the conda-forge channel
      shell: /opt/miniconda3/bin/conda install -y --prefix /opt/miniconda3/envs/jupyterhub -c conda-forge python-dateutil
      become: yes
    - name: Template a modified jupyterhub_config.py file to /etc/jupyterhub/jupyterhub_config.py
      template:
        # need to make this a relative path source
        src: templates/jupyterhub_config_cull_idle_servers.j2
        dest: /etc/jupyterhub/jupyterhub_config.py
        owner: root
        group: "{{ user_name }}"
        mode: '0770'
    - name: copy the cull_idle_servers_script into /ect/jpyterhub/cull_idle_servers.py
      copy:
        # need to make this a relative path source
        src: templates/cull_idle_servers.py
        dest: /etc/jupyterhub/cull_idle_servers.py
        owner: root
        group: sudo
        mode: '0644'
      become: yes

    - name: Restart the jupyterhub systemd service
      systemd:
        state: restarted
        name: jupyterhub
      become: yes
