---
- hosts: localhost
  vars:
    do_api_token: "{{ lookup('file','~/.do/do_api_token') }}"
  tasks:
  - name: Gather information about Digital Ocean SSH Keys
    digital_ocean_sshkey_info:
      oauth_token: "{{ do_api_token }}"
    register: ssh_keys

  - debug: var=ssh_keys
