---
- hosts: localhost
  vars:
    do_api_token: "{{ lookup('file','~/.do/do_api_token') }}"
  tasks:
  - name: Gather information about all domains
    digital_ocean_domain_info:
      oauth_token: "{{ do_api_token }}"
    register: resp_out
  - set_fact:
      domain_name: "{{ item.name }}"
    loop: "{{ resp_out.data|json_query(name) }}"
    vars:
      name: "[?name=='engr114.org']"
  - debug: var=domain_name
