---
- hosts: localhost
  tasks:
  - name: Gather information about Digital Ocean SSH Keys
    digital_ocean_sshkey_info:
      oauth_token: "{{ lookup('env','DO_API_TOKEN') }}"
    register: ssh_keys

  - debug: var=ssh_keys
