---
- hosts: localhost
  tasks:
  - name: Gather information about all domains
    digital_ocean_domain_info:
      oauth_token: "{{ lookup('env','DO_API_TOKEN') }}"
    register: resp_out
  - set_fact:
      domain_name: "{{ item.name }}"
    loop: "{{ resp_out.data|json_query(name) }}"
    vars:
      name: "[?name=='engr114.org']"
  - debug: var=domain_name
