# site.yml
# master Ansible playbook that runs all of the other playbooks
# to run:
# $ ansible-playbook site.yml

#- import_playbook: prompts.yml
- import_playbook: get_do_account_info.yml
- import_playbook: get_do_domain_names.yml
- import_playbook: get_do_SSH_key_info.yml
- import_playbook: put_do_SSH_key.yml
- import_playbook: create_do_server.yml
- import_playbook: add_do_server_to_group.yml
#- import_playbook: initial_server_setup.yml
#- import_playbook: install_miniconda.yml
#- import_playbook: install_jupyterhub.yml
#- import_playbook: ssl_cirt.yml
#- import_playbook: cookie_secret_and_proxy_auth_token.yml
#- import_playbook: nginx_install.yml
#- import_playbook: nginx_config.yml
#- import_playbook: jupyterhub_config.yml
#- import_playbook: system_service.yml
#- import_playbook: google_oath.yml
#- import_playbook: custom_login_page.yml
#- import_playbook: cull_idle_servers.yml
