# vars/defaults.yml
---
# vars/local.yml
# make sure this is added to .gitignore
user_name: peter
local_SSH_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
do_api_token: "{{ lookup('file','~/.do/do_api_token') }}"
ssh_key_array: [12XX1,23XX4,454XXX4,98XX15] 

# in vars/host.yml
# make sure this is added to .gitignore
user_name: peter
do_server_ip: 3435.XXX.1X.14X1
domain_name: mydomain.org
email: my.email@college.edu
do_droplet_id: 17XXX694X
sys_packages: ['curl', 'vim', 'git', 'ufw','wget']
